import "@/app/globals.css";
import DesktopNavbar from "@/components/Dashboard/Navbar/DesktopNavbar";
import DesktopSidebar from "@/components/Dashboard/Sidebar/DesktopSidebar";
import MobileSidebar from "@/components/Dashboard/Sidebar/MobileSidebar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <section className="flex sm:gap-20">
        <aside className="w-[270px] sm:block hidden">
          <DesktopSidebar />
        </aside>
        <aside className="block sm:hidden mt-3">
          <MobileSidebar />
        </aside>
        <section className="flex flex-col w-full">
        <nav className="w-full sm:block hidden">
          <DesktopNavbar />
        </nav>
        <main>{children}</main>
        </section>
      </section>
  );
}
