import "@/app/globals.css";
import DesktopSidebar from "@/components/Dashboard/Sidebar/DesktopSidebar";
import MobileSidebar from "@/components/Dashboard/Sidebar/MobileSidebar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="min-h-screen">
      <body className="flex">
        <aside className="w-[270px] sm:block hidden">
          <DesktopSidebar />
        </aside>
        <aside className="block sm:hidden">
          <MobileSidebar />
        </aside>
        <main>{children}</main>
      </body>
    </html>
  );
}
